name: CI/CD e Notificações

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  pr_opened_notification:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Enviar notificação de PR aberto para o Discord
        uses: sarvex/action-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: '📬 Nova Pull Request Aberta'
          color: '16776960'
          description: |
            Uma nova PR está pronta para revisão.
            **Título**: `${{ github.event.pull_request.title }}`
            **Autor**: `${{ github.actor }}`
            **Branch de Origem**: `${{ github.head_ref }}`
            [Clique aqui para revisar a Pull Request](${{ github.event.pull_request.html_url }})

  delivery:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Crio o artefato
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: src/main.py

  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    if: github.event_name == 'push'
    steps:
        - uses: actions/download-artifact@v4
          with:
            name: projetozipado.zip
        - name: Display structure of downloaded artifact
          run: ls -R

  discord_deploy_status:
    runs-on: ubuntu-latest
    needs: deploy
    if: always() && github.event_name == 'push'
    steps:
      - name: Discord notification on success
        if: success()
        uses: sarvex/action-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: '✅ Deploy Concluído com Sucesso'
          color: '3066993'
          description: |
            O deploy na branch **main** foi bem-sucedido.
            **Commit**: `${{ github.event.head_commit.message }}`
            **Autor**: `${{ github.actor }}`
            [Ver detalhes da execução](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Discord notification on failure
        if: failure()
        uses: sarvex/action-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: '❌ Falha no Deploy'
          color: '15158332'
          description: |
            Ocorreu um erro durante o deploy na branch **main**.
            **Commit**: `${{ github.event.head_commit.message }}`
            **Autor**: `${{ github.actor }}`
            [Ver detalhes da execução](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})