name: continuousdelivery.yml
on:
  push:
    branches:
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: simulando continuous delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path:
            main.py

  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
        - uses: actions/download-artifact@v4
          with:
            name: projetozipado.zip

        - name: Display structure of downloaded artifact
          run: ls -R

  discord:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Discord notification on success
        if: success()
        uses: ts-pr-discord-webhook/action@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: '✅ Deploy Concluído com Sucesso'
          color: '3066993'
          description: |
            O deploy na branch **main** foi bem-sucedido.
            **Commit**: `${{ github.event.head_commit.message }}`
            **Autor**: `${{ github.actor }}`
            [Ver detalhes da execução](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Discord notification on failure
        if: failure()
        uses: ts-pr-discord-webhook/action@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: '❌ Falha no Deploy'
          color: '15158332'
          description: |
            Ocorreu um erro durante o deploy na branch **main**.
            **Commit**: `${{ github.event.head_commit.message }}`
            **Autor**: `${{ github.actor }}`
            [Ver detalhes da execução](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
